apiVersion: apps/v1
kind: Deployment
metadata:
  name: runners-app
spec:
  selector:
    matchLabels:
      app: runners-app
  replicas: 1
  template:
    metadata:
      labels:
        app: runners-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - image: docker.io/egsmartin/runners-app:latest
          name: runners-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 9000
          env:
            - name: ENV
              value: "k8s"